# Generated by Django 2.1 on 2018-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
            ],
        ),
    ]
